name: deconz-webserver
base: core24
version: '0.1'
summary: Single-line elevator pitch for your amazing snap
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
confinement: devmode

apps:
  deconz-webserver:
    command: lib/node_modules/deconz-webserver/command.sh
    daemon: simple
    restart-condition: always

parts:
  backend:
    plugin: npm
    source: .
    npm-include-node: true
    npm-node-version: "22.19.0"
