name: deconz-webserver
base: core24
version: '0.1'
summary: Single-line elevator pitch for your amazing snap
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

  armhf:
    build-on: [arm64]    
    build-for: [armhf]

  arm64:
    build-on: [arm64]
    build-for: [arm64]

apps:
  deconz-webserver:
    command: backend/command.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind

  my-electron-app:
    command: electron/command.sh
    extensions: [gnome] 
    plugs:
      - browser-support
      - network-bind
      - home
      - unity7
      - opengl
      - bluez

parts:
  frontend:
    plugin: nil
    source: .
    build-snaps:
      - node/22/stable
    override-build: |
      npm run setup:frontend
      npm run build:frontend

      # Install frontend build to the part's install dir
      mkdir -p $SNAPCRAFT_PART_INSTALL/frontend/dist
      cp -r frontend/dist/* $SNAPCRAFT_PART_INSTALL/frontend/dist/

    stage:
    - frontend/dist


  backend:
    plugin: npm
    source: .
    npm-include-node: true
    npm-node-version: "22.11.0"
    after: [frontend]
    build-snaps:
      - node/22/stable
    stage-packages:
      - libatomic1
    build-packages:
      - build-essential
      - python3
      - python3-pip
      - libsqlite3-dev
      - pkg-config
    override-build: |
      # export PATH=/snap/bin:$PATH

      # Install and build
      npm run setup:backend

      # Copy output to $SNAPCRAFT_PART_INSTALL
      mkdir -p $SNAPCRAFT_PART_INSTALL/backend/public
      cp -r ./backend/* $SNAPCRAFT_PART_INSTALL/backend/
      cp -r $SNAPCRAFT_STAGE/frontend/dist/* $SNAPCRAFT_PART_INSTALL/backend/public

      # In order to have node binary inside installed snap
      craftctl default


  electron-app:
    plugin: nil
    source: .
    after: [frontend]
    build-snaps:
      - node/22/stable
    build-packages:
      - build-essential
      - python3
      - python3-pip
      - libsqlite3-dev
      - pkg-config
    override-build: |
      # export PATH=/snap/bin:$PATH

      # According to package.json (electron build section) the electron app tries to get frontend
      # from frontend/dist folder (relative to where package.json lies)
      mkdir -p $CRAFT_PART_BUILD/frontend/dist
      cp -r $SNAPCRAFT_STAGE/frontend/dist/* $CRAFT_PART_BUILD/frontend/dist

      # Install and build
      npm install
      npm run build:electron

      # Find the actual electron build folder
      ELECTRON_BUILD_DIR=$(find ./dist -maxdepth 1 -type d -name "*linux*unpacked*" | head -n 1)

      if [ -z "$ELECTRON_BUILD_DIR" ]; then
          echo "Error: Electron build folder not found!"
          exit 1
      fi

      # Copy output to $SNAPCRAFT_PART_INSTALL
      mkdir -p $SNAPCRAFT_PART_INSTALL/electron
      cp -r "$ELECTRON_BUILD_DIR"/* $SNAPCRAFT_PART_INSTALL/electron/

      # Copy the shell scripts
      cp -r ./electron/command-shellscripts/* $SNAPCRAFT_PART_INSTALL/electron/