name: deconz-webserver
base: core24
version: '0.1'
summary: Single-line elevator pitch for your amazing snap
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
confinement: strict

# platforms:
#   amd64:
#     build-on: [amd64]
#     build-for: [amd64]

platforms:
  armhf:
    build-on: [armhf]
    build-for: [armhf]

apps:
  deconz-webserver:
    command: lib/node_modules/deconz-webserver/command.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind

  my-electron-app:
    command: command.sh
    extensions: [gnome] 
    plugs:
      - browser-support
      - network-bind
      - home
      - unity7
      - opengl
      - bluez
    environment:
      DISABLE_WAYLAND: '1'
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
      LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu

parts:
  backend:
    plugin: npm
    source: ./backend
    npm-include-node: true
    npm-node-version: "22.19.0"

  electron-app:
    plugin: dump
    source: ./dist/linux-unpacked